Add remind function to .zshrc

diff --git a/dot_zshrc b/dot_zshrc
--- a/dot_zshrc
+++ b/dot_zshrc
@@ -159,5 +159,145 @@ swap () {
 	mv "$1" "$1.temp" && mv "$2" "$1" && mv "$1.temp" "$2";
 }
 
+remind() {
+	local COUNT="$#"
+	local COMMAND="$1"
+
+	# Display help if no parameters or help command
+	if [[ $COUNT -eq 0 || "$COMMAND" == "help" || "$COMMAND" == "--help" || "$COMMAND" == "-h" ]]; then
+		echo "COMMAND"
+		echo "		remind <message> <time>"
+		echo "		remind <command>"
+		echo
+		echo "DESCRIPTION"
+		echo "		Displays notification at specified time"
+		echo
+		echo "EXAMPLES"
+		echo '		remind "Hi there" now'
+		echo '		remind "Time to make dinner" in 5 minutes'
+		echo '		remind "Take a break" in 1 hour'
+		echo '		remind "Are you ready?" at noon'
+		echo '		remind "Dinner" at 16:00'
+		echo '		remind "Meeting" at 1130'
+		echo '		remind list'
+		echo '		remind clear'
+		echo '		remind help'
+		echo
+		return
+	fi
+
+	# Check presence of AT command
+	if ! which at > /dev/null; then
+		echo "remind: AT utility is required but not installed on your system. Install it with your package manager of choice, for example 'sudo pacman -S at'."
+		return
+	fi
+
+	# Run commands: list, clear
+	if [[ COUNT -eq 1 ]]; then
+		if [[ "$COMMAND" == "list" ]]; then
+			# at -l
+			# atq | awk '{print $1}' | xargs -I{} at -c {} | grep notify-send
+			atq | while read -r job_id day month num time rest; do
+				message=$(at -c "$job_id" | grep notify-send | sed -E "s/notify-send '(.*)' 'Reminder' -u critical/\1/")
+				date_str=$(LC_ALL=C date -d "$day $month $num $time $year" + "%Y-%m-%d %H:%M:%S" 2>/dev/null)
+				printf "%s %s - %s\n" "$day" "$time" "$message"
+			done | sort
+		elif [[ "$COMMAND" == "clear" ]]; then
+			at -r $(atq | cut -f1)
+		else
+			echo "remind: unknown command $COMMAND. Type 'remind' without any parameters to see syntax."
+		fi
+		return
+	fi
+
+	# Ensure enough arguments are provided before shifting
+	if [[ COUNT -lt 2 ]]; then
+		echo "remind: missing arguments. Type 'remind help' for usage."
+		return
+	fi
+
+	local MESSAGE="$1"
+	local OP="$2"
+	shift 2
+	local WHEN="$@"
+
+	# Determine time of notification
+	if [[ "$OP" == "in" ]]; then
+		local TIME="now + $WHEN"
+	elif [[ "$OP" == "at" ]]; then
+		local TIME="$WHEN"
+	elif [[ "$OP" == "now" ]]; then
+		local TIME="now"
+	else
+		echo "remind: invalid time operator $OP"
+		return
+	fi
+
+	# Schedule the notification
+	echo "notify-send '$MESSAGE' 'Reminder' -u critical" | at $TIME 2>/dev/null
+	echo "Notification scheduled at ${TIME}"
+}
+
+# remind() {
+# 	local COUNT="$#"
+# 	local COMMAND="$1"
+# 	local MESSAGE="$1"
+# 	local OP="$2"
+# 	shift 2
+# 	local WHEN="$@"
+# 	# Display help if no parameters or help command
+# 	if [[ $COUNT -eq 0 || "$COMMAND" == "help" || "$COMMAND" == "--help" || "$COMMAND" == "-h" ]]; then
+# 		echo "COMMAND"
+# 		echo "		remind <message> <time>"
+# 		echo "		remind <command>"
+# 		echo
+# 		echo "DESCRIPTION"
+# 		echo "		Displays notification at specified time"
+# 		echo
+# 		echo "EXAMPLES"
+# 		echo '		remind "Hi there" now'
+# 		echo '		remind "Time to make dinner" in 5 minutes'
+# 		echo '		remind "Take a break" in 1 hour'
+# 		echo '		remind "Are you ready?" at noon'
+# 		echo '		remind "Dinner" at 16:00'
+# 		echo '		remind "Meeting" at 1130'
+# 		echo '		remind list'
+# 		echo '		remind clear'
+# 		echo '		remind help'
+# 		echo
+# 		return
+# 	fi
+# 	# Check presence of AT command
+# 	if ! which at > /dev/null; then
+# 		echo "remind: AT utility is required but no installed on your system. Install it with your package manager of choice, for example 'sudo pacman -S at'."
+# 		return
+# 	fi
+# 	# Run commands: list, clear
+# 	if [[ COUNT -eq 1 ]]; then
+# 		if [[ "$COMMAND" == "list" ]]; then
+# 			at -l
+# 		elif [[ "$COMMAND" == "clear" ]]; then
+# 			at -r $(atq | cut -f1)
+# 		else
+# 			echo "remind: unknown command $COMMAND. Type 'remind without any parameters to see syntax."
+# 		fi
+# 		return
+# 	fi
+# 	# Determine time of notification
+# 	if [[ "$OP" == "in" ]]; then
+# 		local TIME="now + $WHEN"
+# 	elif [[ "$OP" == "at" ]]; then
+# 		local TIME="$WHEN"
+# 	elif [[ "$OP" == "now" ]]; then
+# 		local TIME="now"
+# 	else
+# 		echo "remind: invalid time operator $OP"
+# 		return
+# 	fi
+# 	# Schedule the notification
+# 	echo "notify-send '$MESSAGE' 'Reminder' -u critical" | at $TIME 2>/dev/null
+# 	echo "Notification scheduled at ${TIME}"
+# }
+
 # export arduino-cli config file path (XDG_CONFIG_HOME)
 export ARDUINO_CLI_CONFIG_FILE="/home/$(whoami)/.config/arduino-cli/arduino-cli.yaml"
